var NumberOfWords = 100

var words = new BuildArray(NumberOfWords)

// Use the following variables to 
// define your random words:
words[1] = "http://shortearn.eu/mcV09"
words[2] = "http://shortearn.eu/K1pouNg"
words[3] = "http://shortearn.eu/XLjs"
words[4] = "http://shortearn.eu/kBeH"
words[5] = "http://shortearn.eu/EZUf6w"
words[6] = "http://shortearn.eu/vAmcszwe"
words[7] = "http://shortearn.eu/ct2Ek2I4"
words[8] = "http://shortearn.eu/cTavW0"
words[9] = "http://shortearn.eu/52f1pJYH"
words[10] = "http://shortearn.eu/RB8TVqFp"
words[11] = "http://shortearn.eu/k8pUN"
words[12] = "http://shortearn.eu/g5sHW"
words[13] = "http://shortearn.eu/zkRSt"
words[14] = "http://shortearn.eu/A0bb"
words[15] = "http://shortearn.eu/o7rTy"
words[16] = "http://shortearn.eu/ECUBQ"
words[17] = "http://shortearn.eu/TCCm"
words[18] = "http://shortearn.eu/0e5Zm"
words[19] = "http://shortearn.eu/P5ICP2"
words[20] = "http://shortearn.eu/bQ6og"
words[21] = "http://shortearn.eu/fJejEOnS"
words[22] = "http://shortearn.eu/eQN1"
words[23] = "http://shortearn.eu/7ndrCj"
words[24] = "http://shortearn.eu/RUATLwd"
words[25] = "http://shortearn.eu/euOp"
words[26] = "http://shortearn.eu/Av76b"
words[27] = "http://shortearn.eu/2sEemS"
words[28] = "http://shortearn.eu/Gw4Bn6"
words[29] = "http://shortearn.eu/pt4uk"
words[30] = "http://shortearn.eu/1TZc8pNH"
words[31] = "http://shortearn.eu/vQaleat"
words[32] = "http://shortearn.eu/1Er8Z"
words[33] = "http://shortearn.eu/U7Xmb4N"
words[34] = "http://shortearn.eu/mCizGuB"
words[35] = "http://shortearn.eu/fIskwLEd"
words[36] = "http://shortearn.eu/afzMGi"
words[37] = "http://shortearn.eu/YXIjvBC"
words[38] = "http://shortearn.eu/dw1Wy"
words[39] = "http://shortearn.eu/sGqpar"
words[40] = "http://shortearn.eu/qsMWC65"
words[41] = "http://shortearn.eu/pjSBwuK"
words[42] = "http://shortearn.eu/f3X19mqm"
words[43] = "http://shortearn.eu/S4iFi7"
words[44] = "http://shortearn.eu/4y0bExlH"
words[45] = "http://shortearn.eu/spM2Y"
words[46] = "http://shortearn.eu/5jL0keu"
words[47] = "http://shortearn.eu/vyJd3"
words[48] = "http://shortearn.eu/XuSAME5"
words[49] = "http://shortearn.eu/6yEKNKb1"
words[50] = "http://shortearn.eu/QZQh"
words[51] = "http://shortearn.eu/8ZJ146I"
words[52] = "http://shortearn.eu/oeLy"
words[53] = "http://shortearn.eu/qEGbfF2"
words[54] = "http://shortearn.eu/Bif1b"
words[55] = "http://shortearn.eu/mqdx"
words[56] = "http://shortearn.eu/rPJh"
words[57] = "http://shortearn.eu/7zCN2lyE"
words[58] = "http://shortearn.eu/YdA9Lrm"
words[59] = "http://shortearn.eu/pwR21Ir"
words[60] = "http://shortearn.eu/qKFck"
words[61] = "http://shortearn.eu/zQhH0eUW"
words[62] = "http://shortearn.eu/sAspJup"
words[63] = "http://shortearn.eu/T2uJmG"
words[64] = "http://shortearn.eu/dYuul"
words[65] = "http://shortearn.eu/P8riqS"
words[66] = "http://shortearn.eu/fY9K"
words[67] = "http://shortearn.eu/5pyQsuBq"
words[68] = "http://shortearn.eu/PaWog2g"
words[69] = "http://shortearn.eu/5dSUuu"
words[70] = "http://shortearn.eu/CM6X1HG"
words[71] = "http://shortearn.eu/P60oY"
words[72] = "http://shortearn.eu/aOya9"
words[73] = "http://shortearn.eu/ecnBcs0"
words[74] = "http://shortearn.eu/fIww1gh"
words[75] = "http://shortearn.eu/PbH2"
words[76] = "http://shortearn.eu/OHzUnn8h"
words[77] = "http://shortearn.eu/nOtw9L"
words[78] = "http://shortearn.eu/xJ2cq"
words[79] = "http://shortearn.eu/JkYstFR"
words[80] = "http://shortearn.eu/cHWAu3"
words[81] = "http://shortearn.eu/yFVx7M"
words[82] = "http://shortearn.eu/kh2Zi0"
words[83] = "http://shortearn.eu/HwC5X"
words[84] = "http://shortearn.eu/EeDpogzF"
words[85] = "http://shortearn.eu/ftlmkBX"
words[86] = "http://shortearn.eu/Y2pQt"
words[87] = "http://shortearn.eu/ia9Vqzv"
words[88] = "http://shortearn.eu/UzpRmq"
words[89] = "http://shortearn.eu/5kMYdrQ"
words[90] = "http://shortearn.eu/jXXLwU"
words[91] = "http://shortearn.eu/1w09stP4"
words[92] = "http://shortearn.eu/LoP9i"
words[93] = "http://shortearn.eu/ZMWagqRN"
words[94] = "http://shortearn.eu/FufJ"
words[95] = "http://shortearn.eu/LXrg3S4"
words[96] = "http://shortearn.eu/c3Ao"
words[97] = "http://shortearn.eu/QbQX"
words[98] = "http://shortearn.eu/rL58Qi"
words[99] = "http://shortearn.eu/rm1c9G"
words[100] = "http://shortearn.eu/IDIDeJVa"


function BuildArray(size){
this.length = size
for (var i = 1; i <= size; i++){
this[i] = null}
return this
}

function PickRandomWord(frm) {
// Generate a random number between 1 and NumberOfWords
var rnd = Math.ceil(Math.random() * NumberOfWords)

// Display the word inside the text box
frm.WordBox.value = words[rnd]
}